clearer error

diff --git a/mail/ban_mailman b/mail/ban_mailman
--- a/mail/ban_mailman
+++ b/mail/ban_mailman
@@ -18,7 +18,7 @@ MAILMAN_BIN='/usr/lib/mailman/bin'
 let ID=$(id -un)
 
 if [ "$ID" != "mailman" ]
-	then echo "Run this script only as mailman.  Aborting."; exit 1
+	then echo "Run this script only as mailman instead of $ID.  Aborting."; exit 1
 	else true
 fi
 
